# Created 2022-07-20 Wed 16:06
#+title: Contributing to the project
** Filing a bug

Before filing a bug or writing a patch, please check the [[https://github.com/Reikimann/TuxDocs/tree/Readme-edits][development version]] to see if the issue has been fixed.

Issues can be filed [[https://github.com/Reikimann/TuxDocs/issues][here]].

** Pushing changes

Changes should always be done to the pushed to the Readme-edits branch. The main branch is only for official releases.

** When developing

If you want to help us with this project, there are a few guidelines that you need to follow.

1. If you want to add a developer note, please do it like this:

   #+begin_src markdown
     Dev-note: <your dev-note>
   #+end_src

   This allows us to find and remove all dev-notes, before an official release.

2. When writing code blocks always specify the language; markdown for examples like the one above and bash/zsh for the terminal.

3. When showing terminal commands always start the line with a "$", indicating the command-line.

   #+begin_src shell
     $ <command> # Explanation for flags if any
   #+end_src

4. Heading, codeblocks and lists should always be surrounded by a blank line.

5. More rules will come..
