* Technical Terminologies

In this article we will cover some techinal terminology, you can use ~ctrl + ~f~ and search for the term your are looking for.

** Command Flags 

A commad flag allows you to specify extra options when running a command, they could look like this:

#+begin_src bash 
$ ls -l # -l = list view
$ touch -h # Opens the help page
#+end_src

They can also come in expanded versions 

#+begin_src bash 
$ ls --long # Expanded version of -l
$ touch --help # Opens the help page
#+end_src

As you can see they have dubble dashes to signal that they are longer than one character, in that sense you can combine the tiny flags 

#+begin_src bash 
$ ls -la # List view and shows hidden files 
#+end_src

** POSIX

...

** TTY

...

** Shells

...

** Distro

A distro is like a linux flavor, you should never jude a distro by its looks, obviously some distros are built for that but what usually differentiates each distro is the underlying systems.

Arch uses packman as its package manager and debian uses apt. Obviously I will try to not go into too much detail here so if you wanna read more about them click [[https://www.educba.com/linux-distributions/][here]].

A common missconseption is that of "beginner distros", here at the Tux Cult we dont belive in such things. We belive that there are distros that you start with and you can choose from what

Dev-note: Not exactly sure what to write here

** Window manager (WM)

A window manager (WM) is system software that controls the placement and appearance of windows within a windowing system in a graphical user interface (GUI). It can be part of a desktop environment (DE) or be used standalone. 

\- From the arch wiki (Also a great place to find awners to your questions) you can read more from them [[https://wiki.archlinux.org/title/Window_manager][here]].

But i do also want to try and explain it in english, a window manager is the software that tells your system how each window should interact with eachother, how they move look etc.

Commen Window Managers sound like Gnome, I3, wdm, KDE plasma etc. dont think these are the only WMs out there, I think I've lost count by now.

** Desktop manager

...

** Window enviroment

...

** Building from source.
